### ISSUE TITLE
Bug: The fixed header disappear when you get to the end of the page.

### ISSUE THREAD

**Issue by Gyomb** [renaudMaupoux/config-site-base-v2.0-master#6]
## ENVIRONMENT
any (_test/,  _prod/ or even _dev)
## STEPS TO REPRODUCE
1. Got to the html page
2. scroll down a little
   => The header remains visible
3. scroll to the bottom
   => when you reach the bottom of the page, the header disappear
4. scroll back up a little
   => the header doesn't re-appear
5. scroll back up to the top
   => the header is visible again

**Comment by renaudMaupoux** [comment]
I fixed the main problem of scroll by adding a height and overflow on html tag in sass/layout/layout-commun.scss

**Comment by Gyomb** [comment]
I tested the [modification](https://github.com/renaudMaupoux/config-site-base-v2.0-master/commit/1acd417dc0e921ee2cc121763d5ebd600714ad99). But unfortunately, it introduces a new bug in the bottom: the "back to top" button and the  last icons are cropped.

**Comment by renaudMaupoux** [comment]
Last [modification](https://github.com/renaudMaupoux/config-site-base-v2.0-master/commit/d3323de4b08db56835fe91cdde792b57f5238e61) fixed this bug. .site-content is usefull adding to .site-pusher
