### ISSUE TITLE
Q: What about #site-cache?

### ISSUE THREAD

**Issue by Gyomb** [renaudMaupoux/config-site-base-v2.0-master#7]
What is the purpose of `#site-cache` in index.html and communs/js/site.js ?

**Comment by renaudMaupoux** [comment]
#site-cache is used to hide #site-pusher and #site-content like an overlay as users click on menu burger.
Users can also click on it to see the website again. A little Jquery file is used for that (/site.js)

**Comment by Gyomb** [comment]
OK :-)
